[package]
name = "itp1"
authors = ["curekoshimizu"]
version = "0.1.0"
edition = "2018"
pulish = false

# dependencies added to new project
[dependencies]
io_lib = { path = "../../competition_lib/io_lib" }

[profile.release]
lto = true
panic = 'abort'
